name: test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os:
          - 'macos-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bats
        run: npm install -g bats

      - name: test
        run: make test
